### ISSUE TITLE
Mapping from ocd_id to FEC identifiers

### ISSUE THREAD

**Issue by coletl** [openstates/enhancement-proposals#23]
Thanks for the great work. I'd like to request a lookup table mapping OpenStates ocd_ids to the FEC's candidate identifiers. I recognize it could be a significant challenge given the amount of identifying information you have to work with, but I think this mapping would go a long way in linking to data sets beyond state legislation. Here's the info from FEC's [API docs](https://api.open.fec.gov/developers/#/candidate/get_candidate__candidate_id__):

> **candidate_id** (string): A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.

The FEC ID is commonly used in campaign-finance databases. The Congress GitHub even hosts a mapping of FEC IDs to their own legislator IDs [here](https://github.com/unitedstates/congress-legislators).

**Comment by jamesturk** [comment]
Thanks for the comments & suggestion.  The main issue here is that state legislators do not file with the FEC, but instead with their state's equivalent where one exists.  The FEC only has jurisdiction over federal elections.  The equivalent would probably be to link to https://www.opensecrets.org/ data (they recently merged with NIMP, which aggregates state legislative campaign finance data)

**Comment by coletl** [comment]
Of course! I'm sorry, I should have posted this to the ProPublica GitHub. I've just started working with both databases at the same time and keep mixing them up. But in case you ever want to link state legislators to future congressional campaigns, that CSV does have opensecrets_id and fec_id.
